version: 2.1
jobs:
  deploy_app:
    working_directory: ~/sample
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: .envファイルへAPIキーを追加する
          command: |
            echo DEBUG=${ENV} > ~/.env
            echo API_KEY=${API_KEY} >> ~/.env
            echo AUTH_DOMAIN=${AUTH_DOMAIN} >> ~/.env
            echo PROJECT_ID=${PROJECT_ID} >> ~/.env
            echo STORAGE_BUCKET=${STORAGE_BUCKET} >> ~/.env
            echo MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID} >> ~/.env
            echo APP_ID=${APP_ID} >> ~/.env
            ls -al
            cat .env
      - run:
          name: npmパッケージをインストールする
          command: |
            npm install
      - run:
          name: ビルドを実行する
          command: |
            npm run build
      - run:
          name: firebase-toolsをインストールする
          command: |
            npm install --dev firebase-tools
      - run:
          name: firebase hostingへデプロイする
          command: |
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - deploy_app:
          filters:
            branches:
              only: master
